<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Helpers;

class Cliente extends Model
{
    public $timestamps = false;
    protected $table = 'Clientes';
    protected $primaryKey = 'Numero';
    protected $fillable = [
        'Numero', 
        'Nombre', 
        'Rfc',
        'Calle',
        'noExterior',
        'noInterior',
        'Colonia',
        'Localidad',
        'Referencia',
        'Municipio',
        'Estado',
        'Pais',
        'CodigoPostal',
        'Agente',
        'Anotaciones',
        'Contacto',
        'Telefonos',
        'Celular',
        'Nextel',
        'Email1',
        'Email2',
        'Email3',
        'Cuenta',
        'CuentaServicio',
        'FormaPago',
        'MetodoPago',
        'UsoCfdi',
        'NumCtaPago',
        'Ieps',
        'PrecioFijo',
        'FacturarAlCosto',
        'Bloquear',
        'Addenda',
        'Juridico',
        'Plazo',
        'Credito',
        'Saldo',
        'Tipo',
        'ClienteRefacciones',
        'ClienteRefaccionesPotencial',
        'AgenteRefacciones',
        '[Refacciones Contacto]',
        '[Refacciones Tel Oficina]',
        '[Refacciones Tel Celular]',
        '[Refacciones ID Nextel]',
        '[Refacciones Email]',
        '[Refacciones Anotaciones]',
        'ClienteServicio',
        'ClienteServicioPotencial',
        'AgenteServicio',
        '[Servicio Contacto]',
        '[Servicio Tel Oficina]',
        '[Servicio Tel Celular]',
        '[Servicio ID Nextel]',
        '[Servicio Email]',
        '[Servicio Anotaciones]',
        'ClienteVentas',
        'ClienteVentasPotencial',
        'AgenteVentas',
        '[Ventas Contacto]',
        '[Ventas Tel Oficina]',
        '[Ventas Tel Celular]',
        '[Ventas ID Nextel]',
        '[Ventas Email]',
        '[Ventas Anotaciones]',
        'Vendedor',
        '[Ventas Vendedor]',
        '[Ventas Industria]',
        '[Ventas Clasificacion Del Cliente]',
        '[Ventas Cobertura]',
        '[Ventas Tamaño Flotilla]',
        '[Ventas Principal Marca Que Maneja]',
        '[Ventas Penetracion Volvo]',
        '[Ventas Penetracion Mack]',
        '[Ventas Principal Aplicacion]',
        '[Ventas Edad de la Flotilla]',
        '[Ventas Status de Venta]',
        '[Ventas Cliente Activo]',
        '[Ventas Razon]',
        '[Ventas Compra Promedio Anual]',
        '[Que Modelos Compran]',
        '[Ventas Fecha de Ultima Venta de Unidad]',
        '[Ventas Fecha de Ultimo Servicio]',
        '[Ventas Fecha de Ultima Refaccion]',
        'UnidadBUS',
        'UnidadTRUCK',
        'Prospecto',
        'Status'
    ];
}
